//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeWCFSelfHosting.calService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="calService.ICalcService")]
    public interface ICalcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/ConcatIntValue", ReplyAction="http://tempuri.org/ICalcService/ConcatIntValueResponse")]
        string ConcatIntValue(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/ConcatIntValue", ReplyAction="http://tempuri.org/ICalcService/ConcatIntValueResponse")]
        System.Threading.Tasks.Task<string> ConcatIntValueAsync(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/ConcatStringValue", ReplyAction="http://tempuri.org/ICalcService/ConcatStringValueResponse")]
        string ConcatStringValue(string value1, string value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/ConcatStringValue", ReplyAction="http://tempuri.org/ICalcService/ConcatStringValueResponse")]
        System.Threading.Tasks.Task<string> ConcatStringValueAsync(string value1, string value2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcServiceChannel : ConsumeWCFSelfHosting.calService.ICalcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcServiceClient : System.ServiceModel.ClientBase<ConsumeWCFSelfHosting.calService.ICalcService>, ConsumeWCFSelfHosting.calService.ICalcService {
        
        public CalcServiceClient() {
        }
        
        public CalcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConcatIntValue(int value1, int value2) {
            return base.Channel.ConcatIntValue(value1, value2);
        }
        
        public System.Threading.Tasks.Task<string> ConcatIntValueAsync(int value1, int value2) {
            return base.Channel.ConcatIntValueAsync(value1, value2);
        }
        
        public string ConcatStringValue(string value1, string value2) {
            return base.Channel.ConcatStringValue(value1, value2);
        }
        
        public System.Threading.Tasks.Task<string> ConcatStringValueAsync(string value1, string value2) {
            return base.Channel.ConcatStringValueAsync(value1, value2);
        }
    }
}
